import mod1 from './my_async';
import create from './ch01_creation/create';
import empty from './ch01_creation/empty';
import from$ from './ch01_creation/from';
import fromEvent from './ch01_creation/fromEvent';
import fromPromise from './ch01_creation/fromPromise';
import interval from './ch01_creation/interval';
import of$ from './ch01_creation/of';
import range from './ch01_creation/range';
import throw$ from './ch01_creation/throw';

//mod1();
//create();
//empty();
//from$();
//fromEvent();
//fromPromise();
//interval();
//of$(1, 2, 3, 4, 5);
//range();
throw$();